import Anthropic from "@anthropic-ai/sdk";

const client = new Anthropic();

const EXTRACTION_PROMPT = `You are extracting financial data from an Israeli pension report page (generated by Surense platform).

Extract ALL data visible on this page into structured JSON. The page may contain:

1. **Summary page (ריכוז נתונים כספיים)**: Extract total_savings (סך החסכון שצברת), total_equity (סך הוני מהחסכון), monthly_deposits (סך הפקדות חודשי), projected_pension_full (סך קצבה חזויה כולל הפקדות), projected_pension_base (סך קצבה חזויה ללא הפקדות), and breakdowns by product type.

2. **Insurance summary (ריכוז כיסויים ביטוחיים)**: Extract health_insurance_exists (boolean for ביטוח בריאות), life_insurance_amount (ביטוח חיים משכנתא), disability_coverage_amount (סך הכיסויים לאובדן כושר עבודה).

3. **Savings product detail (פירוט מוצרי חסכון)**: For each fund on the page, extract: provider (e.g. הראל, הפניקס, מגדל), product_name, fund_number (מספר קופה), product_type (pension/education_fund/severance_fund/investment_fund/savings_policy), investment_track (e.g. "S&P 500 עוקב מדד", "מניות", "השתלמות מניות"), track_code (קוד מסלול), balance (סה"כ צבירה), savings_capital (תגמולים להון), savings_pension (תגמולים לקצבה), severance_capital (פיצויים להון), severance_pension (פיצויים לקצבה), monthly_deposit (הפקדה שוטפת למוצר), salary_for_product (שכר למוצר), deposit_fee_pct (ד.מ מהפקדה %), balance_fee_pct (ד.מ מצבירה %), join_date (מועד הצטרפות למוצר), status (סטטוס: active/inactive), employment_status (מעמד: employed/self_employed), employer (מעסיק), power_of_attorney (מיפוי כוח), monthly_return_pct (תשואה חודש דוח %), yearly_return_pct (תשואה מצטברת מתחילת שנה %), cumulative_return_36m_pct (תשואה מצטברת 36 חודשים %), cumulative_return_60m_pct (תשואה שנתית ממוצעת 60 חודשים %), projected_pension_base (קצבה חזויה ללא הפקדות), projected_pension_full (קצבה חזויה כולל הפקדות), as_of_date (נכון ליום).

4. **Insurance product detail (פירוט מוצרי ביטוח)**: For each policy, extract: provider, policy_number, product_type (health/life/disability — infer from context: ביטוח בריאות = health, ביטוח חיים = life, אובדן כושר עבודה = disability), status, premium, power_of_attorney. For each coverage line: coverage_name (סוג כיסוי), coverage_type (life_death/disability/health_premium/health_policy), insured_person (מבוטח), insured_role (primary/spouse/child — מבוטח ראשי = primary, מבוטח משני (בן/בת זוג) = spouse, ילד = child), insured_amount (סכום ביטוח), premium (פרמיה), start_date (תאריך תחילת כיסוי), end_date (תאריך תום כיסוי).

5. **Cover page or letter page**: Extract report_date and client_name if visible.

Return a JSON object with these optional top-level keys:
- "page_type": one of "cover", "letter", "summary", "insurance_summary", "savings_detail", "insurance_detail"
- "report_date": "YYYY-MM-DD" if visible
- "client_name": string if visible
- "summary": { total_savings, total_equity, monthly_deposits, projected_pension_full, projected_pension_base, disability_coverage_amount, life_insurance_amount, health_insurance_exists }
- "savings_products": [array of products found on this page]
- "insurance_products": [array of policies with nested "coverages" array]

Numbers should be plain numbers without currency symbols (e.g., 962767, not "₪962,767"). Dates should be "YYYY-MM-DD" format. Percentages should be decimal numbers as shown (e.g., 0.11 for 0.11%, NOT 0.0011).

If a page has no extractable financial data (e.g., cover page, letter), return { "page_type": "cover" } or { "page_type": "letter" } with report_date and client_name if visible.

Return ONLY valid JSON, no markdown fences, no commentary.`;

export async function extractPage(
  pdfBase64: string,
  pageNumber: number,
  idempotencyKey?: string
): Promise<Record<string, unknown>> {
  const startTime = Date.now();

  const response = await client.messages.create(
    {
      model: "claude-sonnet-4-6",
      max_tokens: 4096,
      messages: [
        {
          role: "user",
          content: [
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            {
              type: "document",
              source: {
                type: "base64",
                media_type: "application/pdf",
                data: pdfBase64,
              },
              cache_control: { type: "ephemeral" },
            } as any,
            {
              type: "text",
              text: `Extract data ONLY from page ${pageNumber} of this PDF.\n\n${EXTRACTION_PROMPT}`,
            },
          ],
        },
      ],
    },
    idempotencyKey ? { idempotencyKey } : undefined
  );

  const latencyMs = Date.now() - startTime;
  const usageAny = response.usage as unknown as Record<string, number>;

  console.log(
    JSON.stringify({
      event: "llm_call",
      model: response.model,
      input_tokens: response.usage.input_tokens,
      output_tokens: response.usage.output_tokens,
      cache_read_input_tokens: usageAny.cache_read_input_tokens ?? 0,
      cache_creation_input_tokens: usageAny.cache_creation_input_tokens ?? 0,
      latency_ms: latencyMs,
      stop_reason: response.stop_reason,
      page: pageNumber,
      feature: "pdf-page-extraction",
    })
  );

  if (response.stop_reason === "max_tokens") {
    throw new Error(
      "extractPage: response was truncated (max_tokens). Increase max_tokens or reduce page complexity."
    );
  }

  const text = response.content
    .filter((block) => block.type === "text")
    .map((block) => (block as { type: "text"; text: string }).text)
    .join("");

  // Strip potential markdown fences even though the prompt forbids them
  const cleaned = text
    .replace(/^```(?:json)?\s*\n?/i, "")
    .replace(/\n?```\s*$/, "")
    .trim();

  let parsed: Record<string, unknown>;
  try {
    parsed = JSON.parse(cleaned);
  } catch (err) {
    throw new Error(
      `extractPage: failed to parse LLM response as JSON. Raw output (first 500 chars): ${cleaned.slice(0, 500)}`
    );
  }

  return parsed;
}
